Revert "apk: update to Git 417a93ceae540444fdbd3f76d1dadf0e15621fdc (2024-11-13)"
This reverts commit b99422bda5e9b1d8ea61b32c6b613fda587ca393 as it was
reported, that it causes issues:

 ERROR: failed to read repositories: /dev/zero: No buffer space available
 ERROR: unable to select packages:
   ca-bundle-20240203-r1:
     error: uninstallable
     arch: all
     satisfies: world[ca-bundle]

Reported-by: xiao bo <peterwillcn@gmail.com>
References: https://github.com/openwrt/openwrt/commit/b99422bda5e9b1d8ea61b32c6b613fda587ca393#commitcomment-149072959
Signed-off-by: Petr Štetiar <ynezz@true.cz>